function preload() {
  /* Cenários */
  imagemCenarioCeu = loadImage('/assets/cenarios/cenario-trovoada.png');
  imagemCenarioAtras = loadImage('/assets/cenarios/cenario-atras.png');
  imagemCenarioChao = loadImage('/assets/cenarios/cenario-chao.png');
  imagemCenarioFrente = loadImage('/assets/cenarios/cenario-frente.png');
  imagemChuva = loadImage('/assets/cenarios/chuva.png');
  /* Herói */
  imagemHeroi = loadImage('/assets/heroi.png');
  /* Inimigos */
  imagemTroncoDeitado = loadImage('/assets/inimigos/tronco-deitado.png');
  imagemTroncoEmPe = loadImage('/assets/inimigos/tronco-pe.png');
  imagemRoda = loadImage('/assets/inimigos/roda.png');
  imagemPoca = loadImage('/assets/inimigos/poca.png');
  imagemOncaPintada = loadImage('/assets/inimigos/onca-pintada.png');
  imagemMacaco = loadImage('/assets/inimigos/macaco.png');
  imagemJavali = loadImage('/assets/inimigos/javali.png');
  imagemPlantaCarnivora = loadImage('/assets/inimigos/plantacarnivora.png');
  imagemUrubu = loadImage('/assets/inimigos/urubu.png');
  imagemCobraRastejante = loadImage('/assets/inimigos/cobra.png');
  imagemCobraBote = loadImage('/assets/inimigos/cobra-bote.png');
  /* Telas */
  imagemTelaInicial = loadImage('/assets/telas/telainicial.png');
  imagemTelaHistoria = loadImage('/assets/telas/historia.png');
  imagemTelaFinal = loadImage('/assets/telas/telafinal.png');
  imagemMorreu = loadImage('/assets/telas/faleceu.png');
  /* Misc */
  myFont = loadFont('/assets/fonte.otf');
  imagemPowerUp = loadImage('/assets/powerup.png');
  /* Sons */
  somDoJogo = loadSound('/assets/sons/jogo.mp3');
  somDoTitulo = loadSound('/assets/sons/intro.mp3');
  somDaHistoria = loadSound('/assets/sons/historia.mp3');
  somDoFuneral = loadSound('/assets/sons/coffindance.mp3');
  somDaMorte = loadSound('/assets/sons/morte.mp3'); 
  somDoEscorrego = loadSound('/assets/sons/deslize.mp3');
  somDaOnca = loadSound('/assets/sons/onca.mp3');
  somDoPulo = loadSound('/assets/sons/pulo.mp3');
  somDoPowerUp = loadSound('/assets/sons/powerup.mp3');
  somDaBatida = loadSound('/assets/sons/hit.mp3');
  somFaleceu = loadSound('/assets/sons/faleceu.mp3');
}